apiVersion: microservices.dmaganto.infra/v1alpha1
kind: ECSTaskdef
metadata:
  name: {{ .Values.serviceName }}-{{ .Values.containerDefinitions | toString | sha256sum | trunc 10 }}
spec:
  compositionSelector:
    matchLabels:
      dmaganto.infra/provider: upbound
      dmaganto.infra/taskdef-type: tenant
  resourceConfig:
    providerConfigName: default
    tenant: {{ .Values.tenant }}
    name: {{ .Values.serviceName }}
    deletionPolicy: Delete
    region: {{ .Values.region }}
  parameters:
    family: {{ .Values.serviceName }}
    task_id: "{{ .Values.containerDefinitions | toString | sha256sum | trunc 10 }}"
    containerDefinitions: |- 
      [  
{{ .Values.containerDefinitions | toPrettyJson | indent 8}}
      ]