env: dev
tenant: tenant1
region: eu-west-1
createCluster: false
clusterName: dev1
serviceName: &serviceName service-offer
replicas: 1
containerDefinitions:
  name: *serviceName
  cpu: 0
#  portMappings: 
#   - containerPort: 8080
#     hostPort: 8080
#     protocol: TCP
  essential: true
  command:
  - sleep
  - 1d
#  mountPoints: []
#  volumesFrom: []
#  environmentFiles: []
#  secrets: []
#  dnsServers: []
#  dnsSearchDomains: []
#  extraHosts: []
#  dockerSecurityOptions: []
#  dockerLabels: {}
#  ulimits: []
#  logConfiguration:
#    logDriver: awslogs
#    options:
#      awslogs-group: service-dev
#      awslogs-region: eu-central-1
#      awslogs-stream-prefix: service-offer
#    secretOptions: []
#  systemControls: []